### PR TITLE
JDK 16 compatibility

### PR DESCRIPTION
**Pull request by twistedsquare**
A few commits to add some more "--add-opens" flags that are required to get things working with JDK 16 (and future JDKs).  Should be backwards compatible with JDK 11, but merge with https://github.com/typetools/checker-framework/pull/4677 .

### CODE REVIEW

**Comment by twistedsquare** [comment]
In JDK 16, the Integer constructors are marked as deprecated and for removal.  In the first version of this change, I switched new Integer -> Integer.valueOf, but then realised this would have large effect on the tests.  So I've switched back to simply `@SuppressWarnings` but this seems to have incurred a test failure in StaticInit and I don't understand why.  You can see it in the ant_test_jdk11 failure in the latest CI run: it fails to annotate the following new Object as `@GUT.quals.Peer` but I'm not sure why this might have changed with the changes that I made.

**Comment by twistedsquare** [comment]
This one is almost ready to merge.  The JDK 8 and JDK 11 CI are passing, but JDK 16 is failing for two reasons.  The test_jdk16 fails I think because of a genuine JDK difference or bug.  This is from Receivers.diff:

```
 // Test receiver insertion on inner class's default constructor.
 final class ScriptBasedMapping {
-  private final class RawScriptBasedMapping {public RawScriptBasedMapping(@checkers.inference.quals.VarAnnot(0) ScriptBasedMapping ScriptBasedMapping.this) { super(); }}
+  private final class RawScriptBasedMapping {public RawScriptBasedMapping(@checkers.inference.quals.VarAnnot(0) ScriptBasedMapping.RawScriptBasedMapping this) { super(); }}
 }
```

It looks like previously the annotation went on the outer instance, but now it's going on the inner instance?  Any hints on that one would be appreciated.

The misc_jdk16 is also failing, but I think that will pass once the run-google-java-format PR is merged... which I see you've just done while I was writing this comment.  So if we can work out how to fix the first issue, the second should be fine when the CI is re-run.

**Comment by mernst** [comment]
The new behavior for `Receivers.java` is incorrect.  I will investigate.

**Comment by mernst** [comment]
@twistedsquare A small request:  After you have opened a pull request, could you please only do regular pushes, not force-pushes?  The latter lead to merge conflicts.  Those merge conflicts are not difficult to resolve, but regular pushes would avoid them entirely.  Thanks!

**Review by mernst — APPROVED** [review]

**Pull request merged**
