### PR TITLE
Expose the IndexFileWriter annotation printing code

### PR DESCRIPTION
**Pull request by kelloggm**
Merge together with [typetools/checker-framework#2871](https://github.com/typetools/checker-framework/pull/2871).

This enables re-use of this code in [typetools/checker-framework#2871](https://github.com/typetools/checker-framework/pull/2871).

Also fixes a minor bug related to how longs are printed, and generally cleans up this code.

### CODE REVIEW

**Comment by mernst** [comment]
@kelloggm Could you make the CI job pass?  Thanks.

**Comment by kelloggm** [comment]
This code causes downstream problems, because it appends an `L` after long literals.

In particular, https://github.com/typetools/annotation-tools/blob/2065cf945baee0379ba4e855b8fc0b3f81bd0da7/scene-lib/src/scenelib/annotations/io/IndexFileParser.java#L391 expects just an integer there.

This is obviously a bug in `IndexFileParser`, but I'm unsure whether I should fix it or just move this code back into `SceneToStubWriter` (where I put it originally...), because it could be the case that the JAIF specification precludes this change. That would be a bug in that specification, but this change will likely break any other JAIF parsers that exist (are there any? I don't know...).

@mernst, what do you think the right choice is? Is the AFU obligated not to change the JAIF file format?

**Comment by mernst** [comment]
You are proposing to relax the JAIF file format rather than change it incompatibly, I think:  you want the file format to permit but not require a trailing "L".  Is that correct?  Or would it require "L" whenever the type is long, to indicate the type?

**Comment by kelloggm** [comment]
> You are proposing to relax the JAIF file format rather than change it incompatibly

I am proposing to relax the format by permitting an 'L' after long literals, consistent with the rules for Java source code.

I'm concerned that this is a breaking change, regardless, for existing parsers. Are there other parsers besides `IndexFileParser` in the AFU that I need to worry about?

**Comment by mernst** [comment]
> Are there other parsers besides `IndexFileParser` in the AFU that I need to worry about?

Not to my knowlegde.

**Pull request merged**
