### PR TITLE
Issue 144 work

### PR DESCRIPTION
**Pull request by wmdietl**
DO NOT MERGE.

As a first step to fixing #144 I wanted to see whether there are any tests for ASTPaths.
It seems to me that the tests in `annotation-tools/annotation-file-utilities/tests/converted` are currently not executed at all.
This PR adds the Makefile changes to execute the converted tests, which results in 15 failed tests:

```
     [exec] === RESULTS ===
     [exec] 
     [exec] ASTInsert.diff ...OK
     [exec] AnonInner.diff ...OK
     [exec] ArrayMultiDim.diff ...OK
     [exec] ArrayParamSimple.diff ...OK
     [exec] ArrayReturnTypeSimple.diff ...OK
     [exec] BoundClassMultiple.diff ...FAILED
     [exec] BoundClassSimple.diff ...OK
     [exec] BoundMethodMultiple.diff ...FAILED
     [exec] BoundMethodSimple.diff ...FAILED
     [exec] CastInsert.diff ...OK
     [exec] ClassAnnotationParameter.diff ...OK
     [exec] ClassListAnnotationParameter.diff ...OK
     [exec] ClassSimple.diff ...OK
     [exec] ComplexLocationOne.diff ...OK
     [exec] ComplexLocationTwo.diff ...OK
     [exec] ConstructorParam.diff ...OK
     [exec] ConstructorParamMultiple.diff ...OK
     [exec] ConstructorReceivers.diff ...FAILED
     [exec] ConstructorReturn.diff ...OK
     [exec] Date.diff ...OK
     [exec] DeclarationAnnotation.diff ...OK
     [exec] DuplicateAnnotation.diff ...OK
     [exec] make[1]: *** [results] Error 1
     [exec] make: *** [converted] Error 2
     [exec] EnumAnnotationParameter.diff ...OK
     [exec] EnumListAnnotationParameter.diff ...OK
     [exec] ExtImpl.diff ...FAILED
     [exec] FieldGenericArray.diff ...OK
     [exec] FieldMultiple.diff ...FAILED
     [exec] FieldSimple.diff ...OK
     [exec] FieldSimpleArray.diff ...OK
     [exec] FieldSimpleGeneric.diff ...OK
     [exec] GenericAnnoBound.diff ...OK
     [exec] GenericArg.diff ...OK
     [exec] GenericCell.diff ...OK
     [exec] GenericCellDoubled.diff ...OK
     [exec] GenericMultiLevel.diff ...OK
     [exec] ImplicitUpper.diff ...FAILED
     [exec] Initializers.diff ...OK
     [exec] InnerClass.diff ...OK
     [exec] InnerClassAnonymous.diff ...OK
     [exec] InnerClassSimple.diff ...FAILED
     [exec] InnerReceivers.diff ...OK
     [exec] InnerTypeResolution.diff ...FAILED
     [exec] InstanceOfMultiple.diff ...OK
     [exec] InstanceOfSimple.diff ...OK
     [exec] IntCell.diff ...OK
     [exec] LocalArray.diff ...OK
     [exec] LocalClass.diff ...OK
     [exec] LocalGeneric.diff ...OK
     [exec] LocalGenericShadow.diff ...OK
     [exec] LocalMultiple.diff ...OK
     [exec] LocalMultipleManyMethods.diff ...OK
     [exec] LocalMultipleManyMethodsShifted.diff ...OK
     [exec] LocalSimple.diff ...OK
     [exec] LocalSimpleMultiple.diff ...OK
     [exec] MatchReturnValue.diff ...OK
     [exec] MemberSelectTypes.diff ...OK
     [exec] MethodCompoundType.diff ...OK
     [exec] MethodMultiple.diff ...OK
     [exec] NewArray.diff ...FAILED
     [exec] NewGeneric.diff ...OK
     [exec] NewInAnnotatedVariable.diff ...FAILED
     [exec] NewMultiple.diff ...OK
     [exec] NewPackage.diff ...OK
     [exec] NewSimple.diff ...OK
     [exec] NonClass.diff ...FAILED
     [exec] NonStandardSpacing.diff ...FAILED
     [exec] Package.diff ...OK
     [exec] ParseType.diff ...OK
     [exec] ReceiverWithThrows.diff ...OK
     [exec] Receivers.diff ...FAILED
     [exec] TypeCastGeneric.diff ...OK
     [exec] TypeCastMultiple.diff ...FAILED
     [exec] TypeCastSimple.diff ...OK
     [exec] TypeParamMethod.diff ...OK
     [exec] Varargs.diff ...OK
     [exec] WildcardAnnoBound.diff ...OK
     [exec] package-info.diff ...OK
     [exec] Passed: 62    Failed: 15
     [exec] Tests failed.
     [exec] Makefile:42: recipe for target 'results' failed
     [exec] make[1]: Leaving directory '.../annotation-tools/annotation-file-utilities/tests/converted'
     [exec] Makefile:43: recipe for target 'converted' failed
```

Before spending time on fixing these I wanted to see whether anyone sees an issue with this test setup.
Feel free to push fixes to this branch.

### CODE REVIEW

**Comment by mernst** [comment]
The comment says "do not merge", so I have unassigned myself.

**Comment by wmdietl** [comment]
This PR enables tests that were previously ignored. It shows that there are 15 failures in the test scripts.
Can you review whether the test setup is correct?
We can skip the failing tests to merge this PR or also work on those fixes in this PR.

**Comment by mernst** [comment]
This seems OK to me.  I suggest that we skip the tests, and add separate issues for each different reason for a test failure, rather than coalescing them in this pull request.

**Comment by wmdietl** [comment]
I skipped the failing tests and filed #170 to classify and fix them.

**Comment by mernst** [comment]
I'm not wild about the duplication of the Makefile.  But I don't think that duplication is the end of the world.  So I have no blocking concerns with the test setup.

**Pull request merged**
