### PR TITLE
JDK 16 compatibility fixes (2nd attempt)

### PR DESCRIPTION
**Pull request by twistedsquare**
This is a 2nd attempt at pull request https://github.com/typetools/annotation-tools/pull/403 -- I've redone the commits and as part of a Git SNAFU I've reforked the annotation-tools repository so this has to be a new request (my fault, sorry).

It includes an update to Gradle 7.0, a copy of the caseTreeGetExpressions that has been added to the checker-framework jdk16 branch, and also properly handles a change to CommandLine.parse (which used to take/return arrays but now takes/returns a List) so that it works before and after the change by using reflection.  This should now be mergeable and work on JDK 8, 11 and 16.

In response to the comment on PR 403: my expectation is that it should work and compile on JDK 16.  However life seems not to be that simple!  I've set up CI on my jdk16 branches using Azure as suggested in the documentation.  The results of the latest run [are public](https://dev.azure.com/twistedsquare/checkerframework/_build/results?buildId=12&view=logs&j=11811b1c-d14b-5529-93a4-5f2e1e50e37a).  There seem to be several separate problems.  The JDK 8 and JDK 11 tests are failing due to various individual test failures that I think are nothing to do with my changes: are they failing at the moment on master?  The JDK 16 tests are failing due to a Maven exception that I believe is a [Maven+JDK16 bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=980467) that requires a Maven update in the VM.

### CODE REVIEW

**Comment by mernst** [comment]
@twistedsquare Unfortunately, `google-java-format` is not idempotent.  Here is one example: https://github.com/google/google-java-format/issues/211.  I'm sorry that tripped you up.

All JDK8 and JDK11 tests are now passing, so this can be merged.  A future pull request should get JDK 16 tests passing.

**Comment by mernst** [comment]
Thanks for these changes!

Branch `mernst:jdk16` makes CI run under JDK 16.
Could you pull that into your `jdk16` branch, then open a new pull request?  (Then I can delete my `jdk16` branch.)

Here are two of the failures.

[Running `javadoc` leads to](https://dev.azure.com/mernst22/checker-framework/_build/results?buildId=10677&view=logs&j=c5312d8b-f49a-58cc-d9c6-4b241c10c101&t=8dd3fa11-7f2e-5335-ff22-6e3e2bcf8927) the errors
```
annotation-file-utilities/src/annotator/Main.java:26: error: package com.sun.tools.javac.tree is not visible
scene-lib/src/scenelib/annotations/util/CommandLineUtils.java:3: error: package com.sun.tools.javac.main is not visible
```

[Running `annotator.Main` leads to](https://dev.azure.com/mernst22/checker-framework/_build/results?buildId=10677&view=logs&j=6c961f0f-bc88-5eda-2c8b-e6bda3d7a65b&t=b79d0677-4255-56ce-ace4-cbe504e563b2)
```
Exception in thread "main" java.lang.IllegalAccessError: class scenelib.annotations.util.CommandLineUtils (in unnamed module @0x2baf3d81) cannot access class com.sun.tools.javac.main.CommandLine (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.main to unnamed module @0x2baf3d81
	at scenelib.annotations.util.CommandLineUtils.parseCommandLine(CommandLineUtils.java:21)
	at annotator.Main.main(Main.java:519)
```

**Comment by twistedsquare** [comment]
Thanks -- I've copied from your jdk16 branch and I'll work on the next errors.  I'll open a new PR (and/or update the checker-framework request) once I've got further.

**Comment by mernst** [comment]
Great.  As you might have noticed, I installed Maven 3.8.1 in the VMs that run JDK 16 (for use in CI).

**Pull request merged**
