### PR TITLE
Update Guava from the old version 15 to the current version 21.

### PR DESCRIPTION
**Pull request by wmdietlGC**

### CODE REVIEW

**Comment by mernst** [comment]
The Java 7 build is failing.  The Java 8 build is succeeding.

**Comment by wmdietl** [comment]
Ah, I'll have to use the Java 7 version of Guava 21.

**Comment by smillst** [comment]
Would you please add this change to the change log? (https://github.com/typetools/annotation-tools/blob/master/annotation-file-utilities/changelog.html)

**Comment by wmdietlGC** [comment]
Guava is just an implementation detail of the AFU and nobody should use or depend on the included version. The changelog currently makes no mention of Guava.
Why should this appear in the log?

**Comment by mernst** [comment]
I agree to omit it from the log.

**Pull request merged**
